### ISSUE TITLE
FEAT: Close menu

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#326] opened 2024-09-17 12:22 UTC
### What feature?

Close the menu on the studio page when the user clicks outside of the menu.

**Comment by lfelix3011** [comment] 2024-09-18 00:40
After the modal audio selectors were merged into the next branch, testing revealed a bug. When another modal is open, and a click happens inside that modal, the Menu Body closes. This happens because the system treats the click inside the modal as a click outside the Menu Body. However, the expected behavior is that the Menu Body should stay open when interacting with others modals opened from Menu Body.

Solution:

To fix this issue, we need to update the logic that handles closing the Menu Body. Instead of closing the Menu Body on any outside click, we need to check if the click is inside any expected open modal (e.g., the audio selector modal). If the click is inside another modal, we should prevent the Menu Body from closing.

This will ensure the Menu Body only closes when clicked outside both the Menu and any expected open modals.

**Closed** 2024-09-20 12:16 UTC
Labels: FE, MERGE CONFLICTS
